// framwork/packages/react/src/App.jsx
import { Button, Countdown } from '@opentiny/react'
import './style.css'

const operation = {
  start: () => { },
  reset: () => { }
}

const operate = ({ start, reset }) => {
  operation.start = start
  operation.reset = reset
}

function App() {
  return (
    <>
      <div className="demo-box">
        <h1 className="demo-titile">React</h1>
        <div className="demo-container">
          <div className="tiny-countdown"> <Countdown operate={operate} /> </div>
          <div className="btn-box">
            <Button type="primary" click={() => operation.reset()}>Reset</Button>
            <Button type="danger" click={() => operation.start()}>Start</Button>
          </div>
        </div>
      </div>
    </>
  )
}

export default App

// framwork/packages/solid/src/App.jsx
import { createSignal } from 'solid-js'
import { Button, Countdown } from '@opentiny/solid'

const operation = {
  start: () => { },
  reset: () => { },
  stop: () => { }
}

const operate = ({ start, reset }) => {
  operation.start = start
  operation.reset = reset
}
function App() {

  return (
    <>
      <div class="demo-box">
        <h1 class="demo-titile">Solid</h1>
        <div class="demo-container">
          <div class="tiny-countdown" style="--ti-countdown-font-color:pink;"><Countdown operate={operate}></Countdown></div>
          <div class="btn-box">
            <Button type="primary" onClick={operation.reset()}>Reset</Button>
            <Button type="danger" onClick={operation.start()}>Start</Button>
          </div>
        </div>
      </div>

    </>
  )
}

export default App
