// framwork/packages/components/vue/button/src/pc.vue
<template>
  <button
    class="tiny-button"
    @click="handleClick"
    :disabled="state.buttonDisabled || loading"
    :autofocus="autofocus"
    :type="nativeType"
    :class="[
      type ? 'tiny-button--' + type : '',
      size ? 'tiny-button--' + size : '',
      {
        'is-disabled': state.buttonDisabled,
        'is-loading': loading,
        'is-plain': state.plain,
        'is-round': round,
        'is-circle': circle,
        'is-icon': icon && !loading && (text || $slots.default),
        'is-only-icon': icon && !loading && !(text || $slots.default)
      }
    ]"
    :tabindex="tabindex"
    v-bind="a($attrs, ['class', 'style'], true)"
  >
    <component
      v-if="icon && !loading"
      :is="icon"
      :class="{ 'is-text': text || $slots.default }"
    />
    <slot>
      <span>{{ text }}</span>
    </slot>
  </button>
</template>

<script>
import { renderless, api } from '@opentiny/renderless/button/vue'
import { props, setup, defineComponent } from '@opentiny/vue-common'
import '@opentiny/theme/button/index.less'

export default defineComponent({
  emits: ['click', 'hook-updated'],
  props: [
    ...props,
    'type',
    'text',
    'size',
    'icon',
    'resetTime',
    'nativeType',
    'loading',
    'disabled',
    'plain',
    'autofocus',
    'round',
    'circle',
    'tabindex'
  ],
  setup(props, context) {
    return setup({ props, context, renderless, api })
  }
})
</script>

// dtt-cfc/packages/components/react/button/src/pc.jsx
import { renderless } from '@opentiny/renderless/button/react' // renderless 无渲染层
import { useSetup } from '@opentiny/react-common' // 抹平不同框架的适配层
import '@opentiny/vue-theme/button/index.css' // 复用 TinyVue 的样式文件

export default function Button(props) {
  const { children, text, autofocus, round, circle, icon: Icon, size, nativeType = 'button' } = props

  const { handleClick, state, tabindex, type, $attrs } = useSetup({
    // 通过 common 适配层的 useSetup 处理 props 和 renderless 无渲染层
    props: { ...props, nativeType: 'button', resetTime: 1000 },
    renderless
  })

  const className = [
    'tiny-button',
    type ? 'tiny-button--' + type : '',
    size ? 'tiny-button--' + size : '',
    state.disabled ? 'is-disabled' : '',
    state.plain ? 'is-plain' : '',
    round ? 'is-round' : '',
    circle ? 'is-circle' : ''
  ]
    .join(' ')
    .trim()

  return (
    <button
      className={className}
      onClick={handleClick}
      disabled={state.disabled}
      autoFocus={autofocus}
      type={nativeType}
      tabIndex={tabindex}
      {...$attrs}
    >
      {Icon ? <Icon className={text || children ? 'is-text' : ''} /> : ''}
      <span>{children || text}</span>
    </button>
  )
}
