// mini-tiny-vue/packages/vue/src/button/src/pc.vue
<template>
  <button
    class="tiny-button"
    :class="{ 'is-disabled': state.disabled || disabled, 'is-circle': circle }"
    @click="handleClick"
    :disabled = "state.disabled || disabled"
  >
    <slot>
      <span>Default Button</span>
    </slot>
  </button>
</template>
<script>
import { defineComponent, $prefix, setup , props } from '@opentiny/vue-common'
import { renderless, api } from '@opentiny/renderless/src/button/vue'
import '@opentiny/vue-theme/src/button/index.less'

export default defineComponent({
  name: $prefix + 'Button',
  emits: ['click'],
  props: [...props, 'disabled','resetTime','circle'],
  setup(props, context) {
    return setup({ props, context, renderless, api })
  }
})
</script>

// framwork/packages/components/react/src/button/src/pc.jsx
import renderless from '@opentiny/renderless/button/react'
import { useSetup } from '@opentiny/react-common'
import { IconLoading } from '@opentiny/react-icon'
import '@opentiny/theme/button/index.less'

export default function Button(props) {
  const {
    children,
    text,
    loading,
    autofocus,
    round,
    circle,
    icon: Icon,
    size,
    nativeType = 'button',
  } = props

  const {
    handleClick,
    state,
    tabindex,
    type,
    $attrs
  } = useSetup({
    props,
    renderless
  })

  const className = [
    'tiny-button',
    type ? 'tiny-button--' + type : '',
    size ? 'tiny-button--' + size : '',
    state.buttonDisabled ? 'is-disabled' : '',
    loading ? 'is-loading' : '',
    state.plain ? 'is-plain' : '',
    round ? 'is-round' : '',
    circle ? 'is-circle' : '',
    (Icon && !loading && (text || children)) ? 'is-icon' : '',
  ].join(' ').trim()

  return (
    <button
      className={className}
      onClick={handleClick}
      disabled={state.buttonDisabled || loading}
      autoFocus={autofocus}
      type={nativeType}
      tabIndex={tabindex}
      {...$attrs}
    >
      {loading ? <IconLoading className="tiny-icon-loading tiny-svg-size" /> : ''}
      {(Icon && !loading) ? <Icon className={(text || children) ? 'is-text' : ''} /> : ''}
      <span>{children || text}</span>
    </button>
  )
}
